Areas/DoanVien/Controllers/XemDiemController.cs
using System.Net;
using System.Security.Cryptography;
using Microsoft.AspNetCore.Mvc;
using QLDV.ActionFilter;
using QLDV.Areas.DoanVien.Models;
using QLDV.Areas.QuanLy.Controllers;
using QLDV.Areas.QuanLy.Models;
using QLDV.Data;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory;

namespace QLDV.Areas.DoanVien.Controllers
{
    [CheckSession]
    [Area("DoanVien")]
    [Route("[area]/[controller]/[action]/{id?}")]
    public class XemDiemController : Controller
    {
        QldvContext qldvContext = new QldvContext();
        public IActionResult Index()
        {
            DiemRenLuyen result = new DiemRenLuyen();

            result.tab1s = Tongdiem();
            result.tab2s = Tab2();
            result.tab3s = Tab3();
            result.tab4s = Tab4();
         
            return View(result);
        }
        public List<Models.TongDiem> Tongdiem()
        {
            List<Models.TongDiem> view = new List<Models.TongDiem>();

            var id = HttpContext.Session.GetInt32("LoginId");
            var result = (from eu in qldvContext.EventUsers
                          join e in qldvContext.Events on eu.EventId equals e.Id
                          join s in qldvContext.Semesters on e.SemesterId equals s.Id
                          where eu.UserId == id
                          orderby eu.Id
                          select new
                          {
                              eu.Id,
                              semTitle = s.Title,
                              eveTitle = e.Title,
                              e.Score,
                              eu.Status
                          });


            var Sem = result.Select(x => x.semTitle).Distinct().ToList();

            for (var i = 0; i < Sem.Count; i++)
            {
                Models.TongDiem temp = new Models.TongDiem()
                {
                    Id = i,
                    SemTitle = Sem[i],
                    Count = 0,
                    Total = 0,
                    MaxTotal = 0

                };

                view.Add(temp);

            }

            foreach (var x in view)
            {
                foreach (var y in result)
                {
                    if (x.SemTitle == y.semTitle)
                    {
                        if (y.Status == "Thông qua")
                        {
                            x.Total = x.Total + y.Score;
                        }
                        x.Count = x.Count + 1;
                        x.MaxTotal = x.MaxTotal + y.Score;
                    }

                }
            }

            return (view);
        }

        public List<Models.SuKienThamGia> Tab2()
        {
            List<Models.SuKienThamGia> view = new List<Models.SuKienThamGia>();

            var id = HttpContext.Session.GetInt32("LoginId");
            var result = (from a in qldvContext.EventUsers
                          join b in qldvContext.Events on a.EventId equals b.Id
                          join c in qldvContext.Semesters on b.SemesterId equals c.Id
                          where a.UserId == id && a.Status == "Chưa duyệt"
                          orderby a.Id
                          select new
                          {
                              Id = a.Id,
                              Title = b.Title,
                              Semester = c.Title,
                              Score = b.Score,
                              Image = b.Image
                          });

            foreach( var a in result )
            {
                var temp = new Models.SuKienThamGia();
                temp.Id = a.Id;
                temp.Title = a.Title;
                temp.Semester = a.Semester;
                temp.Score = a.Score;
                temp.Image = a.Image;
                view.Add(temp);
            }     

            return (view);
        }

        public List<Models.SuKienThamGia> Tab3()
        {
            List<Models.SuKienThamGia> view = new List<Models.SuKienThamGia>();

            var id = HttpContext.Session.GetInt32("LoginId");
            var result = (from a in qldvContext.EventUsers
                          join b in qldvContext.Events on a.EventId equals b.Id
                          join c in qldvContext.Semesters on b.SemesterId equals c.Id
                          where a.UserId == id && a.Status == "Thông qua"
                          orderby a.Id
                          select new
                          {
                              Id = a.Id,
                              Title = b.Title,
                              Semester = c.Title,
                              Score = b.Score,
                              Image = b.Image
                          });

            foreach (var a in result)
            {
                var temp = new Models.SuKienThamGia();
                temp.Id = a.Id;
                temp.Title = a.Title;
                temp.Semester = a.Semester;
                temp.Score = a.Score;
                temp.Image = a.Image;
                view.Add(temp);
            }

            return (view);
        }

        public List<Models.SuKienThamGia> Tab4()
        {
            List<Models.SuKienThamGia> view = new List<Models.SuKienThamGia>();

            var id = HttpContext.Session.GetInt32("LoginId");
            var result = (from a in qldvContext.EventUsers
                          join b in qldvContext.Events on a.EventId equals b.Id
                          join c in qldvContext.Semesters on b.SemesterId equals c.Id
                          where a.UserId == id && a.Status == "Từ chối"
                          orderby a.Id
                          select new
                          {
                              Id = a.Id,
                              Title = b.Title,
                              Semester = c.Title,
                              Score = b.Score,
                              Image = b.Image
                          });

            foreach (var a in result)
            {
                var temp = new Models.SuKienThamGia();
                temp.Id = a.Id;
                temp.Title = a.Title;
                temp.Semester = a.Semester;
                temp.Score = a.Score;
                temp.Image = a.Image;
                view.Add(temp);
            }

            return (view);
        }
    }

    
}

Areas/DoanVien/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    	<title>Đoàn Viên</title>
	<meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!-- Google Web Fonts -->
  <link rel="stylesheet" href="~/DoanVien/assets/vendors/bootstrap/bootstrap.min.css">
  <link rel="stylesheet" href="~/DoanVien//assets/vendors/fontawesome/css/all.min.css">
  <link rel="stylesheet" href="~/DoanVien/assets/vendors/themify-icons/themify-icons.css">
  <link rel="stylesheet" href="~/DoanVien/assets/vendors/linericon/style.css">
  <link rel="stylesheet" href="~/DoanVien/assets/vendors/owl-carousel/owl.theme.default.min.css">
  <link rel="stylesheet" href="~/DoanVien/assets/vendors/owl-carousel/owl.carousel.min.css">

  <link rel="stylesheet" href="~/DoanVien/dist/css/style.css">

</head>
<body>
    
	 <!-- Navbar Start -->
<div class="header_area">
        <div class="main_menu" style="background-color:#0D509C">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container box_1620">
          <!-- Brand and toggle get grouped for better mobile display -->
          <a class="navbar-brand logo_h" asp-area="DoanVien" asp-action="Index" asp-controller="Home"><img src="~/DoanVien/assets/img/huy_hieu_doan.png" width="45" alt=""></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse offset" id="navbarSupportedContent">
            <ul class="nav navbar-nav menu_nav justify-content-center">
              <li class="nav-item" id="Trangchu"><a class="nav-link" asp-area="DoanVien" asp-action="Index" asp-controller="Home">Trang chủ</a></li>
              <li class="nav-item" id="Thongtincanhan"><a class="nav-link" asp-area="DoanVien" asp-action="Index" asp-controller="Profile">Thông tin cá nhân</a></li>
              <li class="nav-item" id="sukien"><a class="nav-link" asp-area="DoanVien" asp-action="Index" asp-controller="Events">Sự kiện</a>
              <li class="nav-item"><a class="nav-link" asp-area="DoanVien" asp-action="Article" asp-controller="Home">Bài viết</a></li>
            </ul>
            <ul class="nav navbar-nav" style="border:2px solid black; border-radius:60px" >
              <li class="nav-item submenu dropdown">
                 @{

                                string sessionName = Context.Session.GetString("LoginName");
                                <a class="nav-link"
                                   href="#"
                                   id="navbarDropdown"
                                   role="button"
                                   data-bs-toggle="dropdown"
                                   aria-expanded="false"
                                   style="justify-content:center;align-items:center;display:flex;width:180px;height:0px">
                                    @sessionName
                                </a>

                            }
                <ul class="dropdown-menu" style="margin-top:5px">
                  
                  <li class="nav-item"><a class="nav-link" asp-action="Index" asp-controller="XemDiem" asp-area="DoanVien">Điểm rèn luyện</a></li>
                  <li class="nav-item"><a class="nav-link" asp-area="QuanLy" asp-controller="Home"  asp-action="DangXuat">Đăng xuất</a></li>
                </ul>
              </li>
            </ul>
          </div> 
        </div>
      </nav>
    </div>
 </div>
    <!-- Navbar End -->

    @RenderBody()

   
    <!-- Footer Start -->
    <footer class="footer-area section-padding">
    <div class="container">
      <div class="row">
        <div class="col-lg-3  col-md-6 col-sm-6">
          <div class="single-footer-widget">
            <h6>Quản lí đoàn viên</h6>
            <p>
             Đươc thực hiện bởi nhóm 7
            </p>
          </div>
        </div>
        <div class="col-lg-4  col-md-6 col-sm-6">
          <div class="single-footer-widget">
            <h6>Thành viên nhóm</h6>
            <p>Phạm Ngọc Thiết</p>
            <p>Trương Trọng Hùng</p>
            <p>Nguyễn Đức Tùng Lâm</p>
    </div>
  </footer>
   
    <!-- Footer End -->
    
</body>
</html>