Areas/DoanVien/Models/TongDiem.cs
namespace QLDV.Areas.DoanVien.Models
{
    public class TongDiem
    {
        public int Id { get; set; }

        public string SemTitle { get; set; }

        public int Count { get; set; }
        public int Total { get; set; }

        public int MaxTotal { get; set; }
    }
}

Areas/QuanLy/Controllers/TongDiemController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Mvc.TagHelpers;
using QLDV.Areas.QuanLy.Models;
using QLDV.Data;

namespace QLDV.Areas.QuanLy.Controllers
{
    public class TongDiemController : Controller
    {
        private readonly IWebHostEnvironment webHostEnvironment;
        QldvContext qldvContext = new QldvContext();
        public TongDiemController(IWebHostEnvironment webHost)
        {
            webHostEnvironment = webHost;
        }
        [Area("QuanLy")]
        [Route("[area]/[controller]/[action]/{id?}")]
        public IActionResult Index()
        {
            ViewBag.Semester = new SelectList (qldvContext.Semesters.ToList() , "Id" , "Title");
            
            return View();
        }

        [HttpPost]
        public IActionResult TimKiem (int Ki)
        {
            ViewBag.Semester = new SelectList(qldvContext.Semesters.ToList(), "Id", "Title");

            List<TongDiemModel> TongDiem = new List<TongDiemModel>();

            var query = (from a in qldvContext.EventUsers
                         join b in qldvContext.Users on a.UserId equals b.Id
                         join c in qldvContext.Events on a.EventId equals c.Id

                         select new
                         {

                             UserId = b.Id,
                             Users = b.Fullname,
                             Score = c.Score,
                             Status = a.Status,
                             Semsters = c.SemesterId,

                         }).Where(x=>x.Semsters == Ki).ToList();
                         
            var user = query.Select(x=>x.UserId).Distinct();
            
            foreach ( var item in user )
            {
                TongDiemModel temp = new TongDiemModel()
                {
                    UserId = item
                };
                TongDiem.Add(temp);
            }

            foreach (var item in TongDiem )
            {
               foreach (var x in query)
                {
                    if (item.UserId == x.UserId)
                    {
                        item.UserFullName = x.Users;
                        if (x.Status == "Thông qua")
                        {
                            item.Count = item.Count + 1;
                            item.TongDiem = item.TongDiem + x.Score;
                        }
                    }
                }
            }

                return View("/Areas/QuanLy/Views/TongDiem/Diem.cshtml", TongDiem);
        }

   
    }
}

Areas/QuanLy/Views/TongDiem/Diem.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model List<QLDV.Areas.QuanLy.Models.TongDiemModel>
<div class="container-fluid">
    <div class="card">
        <div class="card-body">
            <form class="form-horizontal" method="post" asp-area="QuanLy" asp-controller="TongDiem" asp-action="TimKiem">
                <div class="form-group">
                    <label>
                        Thống kê

                    </label>
                    <div class="row">
                        <div class="col-md-9">
                            <select name="Ki" asp-items="ViewBag.Semester" class="select2 form-select shadow-none"
                                    style="width: 100%; height: 36px">
                            </select>
                        </div>
                        <div class="col-md-2">
                            <button type="submit" class="btn btn-primary">
                                Tìm Kiếm
                            </button>
                        </div>

                    </div>

                </div>
            </form>
        </div>
    </div>


    <div class="card">
        <div class="card-body">
            <div class="table-responsive">
                <table id="zero_config"
                       class="table table-striped table-bordered">
                    <thead>
                        <tr>
                            <th>
                                Mã tài khoản
                            </th>
                            <th>
                                Tên Đoàn viên
                            </th>
                            <th>
                                Số lần tham gia
                            </th>
                            <th>
                                Tổng điểm
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @if (Model != null && Model.Count >= 1)
                        {
                            foreach (var item in Model)
                            {
                                <tr>
                                    <td>
                                        @item.UserId
                                    </td>
                                    <td>
                                        @item.UserFullName
                                    </td>
                                    <td>
                                        @item.Count
                                    </td>
                                    <td>
                                        @item.TongDiem
                                    </td>
                                </tr>
                            }
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>

</div>

Areas/QuanLy/Views/TongDiem/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<div class="container-fluid">
   <div class="card">
       <div class="card-body">
            <form class="form-horizontal" method="post" asp-area="QuanLy" asp-controller="TongDiem" asp-action="TimKiem">
                <div class="form-group">
                    <label>
                        Thống kê

                    </label>
                    <div class="row">
                        <div class="col-md-9">
                            <select name="Ki" asp-items="ViewBag.Semester" class="select2 form-select shadow-none"
                                    style="width: 100%; height: 36px">
                            </select>
                        </div>
                        <div class="col-md-2">     
                            <button type="submit" class="btn btn-primary">
                                Tìm Kiếm
                            </button>
                        </div>

                    </div>

                </div>
           </form>
       </div>
   </div>

</div>